### ISSUE TITLE
Potential typo in ecs params.

### ISSUE THREAD

**Issue by drigio** [awsdocs/amazon-ecs-developer-guide#181]
I think there might be a potential typo in the doc [cmd-ecs-cli-compose-ecsparams.md](https://github.com/awsdocs/amazon-ecs-developer-guide/blob/master/doc_source/cmd-ecs-cli-compose-ecsparams.md)
```yaml
docker_volumes:
      - name: string
        scope: string
        autoprovision:      ### Feel like this should be boolean.
        driver: string
        driver_opts: boolean    ### Instead this has become boolean.
           string: string
        labels:
           string: string
```

For reference I saw this document which mentions `autoprovision` to be boolean and `driver_opts` as string.
If this is probably a typo, I'm more than happy to send in a PR for the fix.
